//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaLibreria.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuthorsByEditorialView
    {
        public string Author { get; set; }
        public int EditorialId { get; set; }
        public string Editorial { get; set; }
    }
}
