//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaLibreria.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

  
    public partial class Book
    {
       
        public Book()
        {
            this.Authors = new HashSet<Author>();
        }
                
        [Key]
        [Display(Name = "ISBN", Prompt = "Ingrese código ISBN", Description = "Código de registro")]
        public int ISBN { get; set; }

        [Required]        
        public int IdEditorial { get; set; }

        [ForeignKey("Editorial")]
        [Display(Name = "Editorial", Description = "Edición de libros")]
        public Editorial Editorial { get; set; }


        [Required]
        [Display(Name = "Título", Description = "Titulo del libro")]
        public string Title { get; set; }


        [Display(Name = "Sinopsis", Description = "Resumen del libro.")]
        [StringLength(50, ErrorMessage = "Máximo 50 caracteres")]
        public string Synpsis { get; set; }


        [Display(Name = "Número de páginas", Description = "Total páginas del libro.")]
        public string Pages { get; set; }

        [NotMapped]
        public virtual Editorial Editorials { get; set; }

        [NotMapped]
        public virtual ICollection<Author> Authors { get; set; }

        

    }
}
