//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaLibreria.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Editorial
    {
        public Editorial()
        {
            this.Books = new HashSet<Book>();
        }
    
        public int Id { get; set; }

        [Display(Name = "Editorial", Description = "Edición de libros")]
        public string Name { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Book> Books { get; set; }
    }
}
