//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaLibreria.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using PruebaLibreria.Entities;
    
    public partial class LibraryEntitiesContext : DbContext
    {
        public LibraryEntitiesContext()
            : base("name=LibraryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Editorial> Editorials { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<AuthorsView> AuthorsView { get; set; }
        public virtual DbSet<AuthorsByEditorialView> AuthorsByEditorialView { get; set; }
    }
}
